###
GET http://localhost:3000/api/v1/building/type/lain
###
GET http://localhost:5678/api/v1/building/60b638a5ad89e441293f1943
###
GET http://localhost:3000/api/v1/building
###
POST http://localhost:3000/api/v1/building
Content-Type: application/json

{
    "uniqueName": "A",
    "name": "Gedung Rektorata",
    "desc": "Gedung rektorat UMP",
    "lat": -7.412207679837826,
    "long": 109.27170037031276,
    "imgurl": "imguurl",
    "typeBuilding": "lain"
}
###
PATCH http://localhost:3000/api/v1/building/6056e33718c5d237589b9e94
Content-Type: application/json

{
    "uniqueName": "J",
    "name": "Fakultas Psikologi",
    "desc": "Fakultas psikologi dibangun dengan cinta",
    "lat": -7.413014350636122,
    "long": 109.27297376316133,
    "imgurl": "imguurl",
    "typeBuilding": "fakultas"
    
}
###
DELETE http://localhost:3000/api/v1/building/60b456f2ebc22043bc321fd9
Content-Type: application/json

{
    "uniqueName": "J",
    "name": "Fakultas Psikologi",
    "desc": "Fakultas psikologi dibangun dengan cinta",
    "lat": -7.03283,
    "long": 109.32424,
    "imgurl": "imguurl"
    
}
###
POST http://localhost:3000/api/v1/users
Content-Type: application/json
# x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzdkNWMxZGE1MDgwMzYwODM1ZDJiZiIsImlhdCI6MTU5OTQ1MjYwNCwiZXhwIjoxNTk5NDU5ODA0fQ.KxWPrAZc11drgjvK3FuLnWFn7quBlTt7qRN3BA8wFf4

{
    "name": "ARUMP",
    "username": "arump",
    "password": "arump123321",
    "email": "arump@admin.id",
    "mobileNum": "088324283238",
    "address": "Wangon",
    "userType": "client"
   
}